version: '3.8'

services:
  mvcapp:
    build: .
    ports:
        - "8080:8080"
    depends_on:
        - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Admin123"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data: