#ESTABLECE LA IMAGEN BASE DE .NET 8 SDK PARA CONSTRUIR LA APLICACION
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

#COPIA LOS ARCHIVOS DEL PROYECTO Y RESTAURA LAS DEPENDECIAS
COPY *.csproj .
RUN dotnet restore

#COPIA EL RESTO DE LOS ARCHIVOS Y COMPILA LA APLICACION
COPY . .
RUN dotnet publish -c Release -o /out

#ESTABLECE LA IMAGEN BASE PARA EL ENTORNO DE RUNTIME
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out .

#EXPONER EL PUERTO EN EL QUE SE EJECUTARA LA APLICACION
EXPOSE 80

#COMANDO DE INICIO
ENTRYPOINT ["dotnet", "DockerBiblioteca.dll"]